import "server-only";
import { createClient } from "@/lib/supabase/server";
import { formatBRL, formatDate, formatInteger } from "./format";
export type Metric={label:string;value:string;detail?:string;tone?:"positive"|"warning"|"negative"|"neutral"}; export type ChartPoint={label:string;primary:number;secondary?:number};
export type ManagementPageData={metrics:Metric[];chart:ChartPoint[];rows:Record<string,string|number|null>[];alerts:{title:string;detail:string;priority:"critical"|"warning"|"info"}[]};
const num=(v:unknown)=>typeof v==="number"?v:typeof v==="string"?Number(v)||0:0; const txt=(v:unknown)=>typeof v==="string"?v:null;
async function view(name:string){const client=await createClient();const result=await client.schema("analytics").from(name).select("*");if(result.error)throw new Error("Não foi possível consultar os dados gerenciais.");return(result.data??[])as Record<string,unknown>[]}
const metric=(label:string,value:unknown,detail?:string,tone:Metric["tone"]="neutral"):Metric=>({label,value:formatBRL(num(value)),detail,tone}); const total=(rows:Record<string,unknown>[])=>rows.reduce((sum,row)=>sum+Math.abs(num(row.signed_value)),0);
async function executive():Promise<ManagementPageData>{const[sales,cash,projection,dre]=await Promise.all([view("sales_summary"),view("cash_current_balance"),view("cash_projection_summary"),view("dre_monthly")]);const s=sales[0]??{},c=cash[0]??{},p=projection[0]??{};return{metrics:[metric("Faturamento",s.invoiced_value,"Vendas confirmadas","positive"),metric("A faturar",s.to_invoice_value),metric("Saldo atual",c.current_balance),metric("Resultado gerencial",dre.reduce((sum,row)=>sum+num(row.amount),0))],chart:[],rows:[],alerts:[...(txt(p.first_negative_cash_date)?[{title:"Caixa projetado negativo",detail:`Primeira ocorrência em ${formatDate(txt(p.first_negative_cash_date))}`,priority:"critical"as const}]:[]),...(txt(p.first_below_minimum_cash_date)?[{title:"Caixa abaixo do mínimo",detail:`Limite cruzado em ${formatDate(txt(p.first_below_minimum_cash_date))}`,priority:"warning"as const}]:[])]}}
async function financial():Promise<ManagementPageData>{const[r,p,or,op,m]=await Promise.all([view("open_receivables"),view("open_payables"),view("overdue_receivables"),view("overdue_payables"),view("financial_movements")]);return{metrics:[metric("A receber",total(r)),metric("A pagar",total(p)),metric("Recebíveis vencidos",total(or),undefined,"warning"),metric("Pagáveis vencidos",total(op),undefined,"warning")],chart:[],rows:m.slice(0,50).map(row=>({Contraparte:"—",Documento:txt(row.omie_id),Vencimento:formatDate(txt(row.due_date)),Valor:formatBRL(Math.abs(num(row.signed_value))),Status:txt(row.status)??"—"})),alerts:[]}}
async function cash():Promise<ManagementPageData>{const[balance,summary,daily]=await Promise.all([view("cash_current_balance"),view("cash_projection_summary"),view("cash_projection_daily")]);const b=balance[0]??{},s=summary[0]??{};return{metrics:[metric("Saldo atual",b.current_balance),metric("Entradas previstas",s.projected_inflows),metric("Saídas previstas",Math.abs(num(s.projected_outflows))),metric("Caixa mínimo",s.minimum_cash)],chart:daily.map(row=>({label:formatDate(txt(row.projection_date)),primary:num(row.closing_balance),secondary:num(row.net_flow)})),rows:daily.slice(0,60).map(row=>({Data:formatDate(txt(row.projection_date)),Abertura:formatBRL(num(row.opening_balance)),Entradas:formatBRL(num(row.inflows)),Saídas:formatBRL(Math.abs(num(row.outflows))),Fechamento:formatBRL(num(row.closing_balance))})),alerts:[]}}
async function dre():Promise<ManagementPageData>{const rows=await view("dre_monthly"),unmapped=rows.filter(row=>row.mapping_status==="unmapped");return{metrics:[metric("Resultado gerencial",rows.reduce((sum,row)=>sum+num(row.amount),0)),{label:"Categorias não classificadas",value:formatInteger(unmapped.length),tone:unmapped.length?"warning":"positive"}],chart:[],rows:rows.slice(0,80).map(row=>({Tipo:txt(row.dre_type),Grupo:txt(row.dre_group),Conta:txt(row.dre_account),Categoria:txt(row.category_name)??"Não classificada",Valor:formatBRL(num(row.amount))})),alerts:[]}}
async function commercial():Promise<ManagementPageData>{const[summaries,pipeline,abc]=await Promise.all([view("sales_summary"),view("sales_pipeline"),view("customer_abc")]);const s=summaries[0]??{};return{metrics:[metric("Vendas",s.total_value),metric("Faturado",s.invoiced_value,undefined,"positive"),metric("A faturar",s.to_invoice_value),metric("Ticket médio",s.average_value)],chart:pipeline.map(row=>({label:txt(row.stage_classification)??"Sem etapa",primary:num(row.total_value),secondary:num(row.sale_count)})),rows:abc.slice(0,30).map(row=>({Cliente:txt(row.customer_name)??"Sem cliente",Valor:formatBRL(num(row.total_value)),"% total":`${num(row.share_percent).toFixed(1)}%`,"% acumulado":`${num(row.cumulative_percent).toFixed(1)}%`,Classe:txt(row.abc_class)})),alerts:[]}}
export async function getManagementPageData(page:string){if(page==="executive"||page==="alerts")return executive();if(page==="financial")return financial();if(page==="cash")return cash();if(page==="dre")return dre();if(page==="commercial")return commercial();return{metrics:[],chart:[],rows:[],alerts:[]}satisfies ManagementPageData}
